FROM arm32v7/node:14-alpine as build

WORKDIR /app

RUN apk update && apk upgrade
RUN apk add --update npm

RUN addgroup -S alpine && adduser -S alpine -G alpine
COPY --chown=alpine:alpine . .

ENV NODE_ENV="production"

RUN npm ci --production
RUN npm run build

USER alpine

# stage 2
FROM arm32v7/nginx:1-alpine

COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
