services:
  be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 0.0.0.0:8000:8000
    command: julia ./src/Server.jl

  fe:
    build:
      context: ./game
      dockerfile: Dockerfile
    volumes:
      - ./game:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
