services:
  be:
    build:
      context: ./backend
      dockerfile: Dockerfile-arm
    command: julia ./src/Server.jl

  fe:
    build:
      context: ./game
      dockerfile: Dockerfile-arm
    ports:
      - 3000:80
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
