services:
  be:
    build:
      context: ./backend
      dockerfile: Dockerfile-Arm
    ports:
      - 0.0.0.0:8000:8000
    command: julia ./src/Server.jl

  fe:
    build:
      context: ./game
      dockerfile: Dockerfile-Arm
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
